# Changes this file are not auto-reloaded.
# Run `bundle exec jekyll serve` again to reload this data.



# Global Data
title: Nick Maclean
description: > # this means to ignore newlines until "baseurl:"
  A simple, whitespace, helvetica based portfolio theme.
  
baseurl:  # the subpath of your site, e.g. /blog/
url:  nicolasmaclean.github.io/-folio-them/



# Build settings
markdown: kramdown
highlighter: rouge

include: ["_pages", "_redirects"]
exclude: ["README.md"]



defaults:
  - scope:
      path: _posts
    values:
      layout: post
      permalink: /posts/:year/:title/



# Pagination
paginate: 15
paginate_path: "/posts/page:num/"